<div class="row" id="powerwidgets">
    <div class="col-md-12 bootstrap-grid sortable-grid ui-sortable">

        <div class="powerwidget red" id="widget7" data-widget-fullscreenbutton="false" role="widget" style="">
            <header role="heading">
                <h2>Detailed information</h2>
                </header>
            <div role="content">
                <div class="inner-spacer">
                    <h2><?=$this->error->message?></h2>
                    <br><br>
                    <table class="table table-striped table-hover margin-0px">
                        <thead>
                        <tr>
                            <th>Class</th>
                            <th>File</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->error->trace as $trace) : ?>
                        <tr>
                            <td><span class="text-dark-blue"><strong><?=$trace->get('class')?></strong></span>::<strong><?=$trace->get('function')?></strong></td>
                            <td><?=$trace->get('file')?> <strong>(line: <?=$trace->get('line')?>)</strong></td>
                        </tr>
                        <?php endforeach; ?>


                    </table>


                </div>
            </div>
        </div>


    </div>
</div>