<html ng-app="app">

<head>

<?php foreach ($this->css as $css): ?>
    <link rel="stylesheet" type="text/css" href="<?=$css?>">
<?php endforeach; ?>

<?php foreach ($this->scripts as $script): ?>
    <script type="text/javascript" src="<?=$script?>"></script>
<?php endforeach; ?>

</head>

<body>

<!--Smooth Scroll-->
<div class="smooth-overflow">
    <!--Navigation-->
    <nav class="main-header clearfix" role="navigation"> <a class="navbar-brand" href="index.html"><span class="text-blue">RASPBERRY</span><span class="text-orange">ADMIN</span></a>

    </nav>

    <!--/Navigation-->

    <!--MainWrapper-->
    <div class="main-wrap">

        <!--Main Menu-->
        <div class="responsive-admin-menu">
            <div class="responsive-menu">ORB
                <div class="menuicon"><i class="fa fa-angle-down"></i></div>
            </div>
            <ul id="menu">
                <li class=""><a href="#" class="submenu downarrow" data-id="tables-sub" title="Tables"><i class="entypo-facebook-squared"></i><span> Facebook API</span></a>
                    <!-- Tables Sub-Menu -->
                    <ul id="tables-sub" class="accordion" style="display: block;">
                        <li><a href="admin-tables.html" title="Timeline"><span> Покатушки</span></a></li>
                        <li><a href="admin-datatables.html" title="Profile"></i><span> PHP</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!--/MainMenu-->

        <!--Content Wrapper-->
        <div class="content-wrapper"><!--Horisontal Dropdown-->

            <!--Breadcrumb-->
            <div class="breadcrumb clearfix">
                <ul>
                    <li><a href="index.html"><i class="fa fa-home"></i></a></li>
                    <li><a href="index.html">Facebook API</a></li>
                    <li class="active">Покатушки</li>
                </ul>
            </div>
            <!--/Breadcrumb-->

            <div class="page-header">
                <h1>Components</h1>
            </div>

            <!-- /Widgets Row End Grid-->
        </div>
        <!-- / Content Wrapper -->
    </div>
    <!--/MainWrapper-->
</div>
<!--/Smooth Scroll-->


<!-- scroll top -->
<div class="scroll-top-wrapper hidden-xs">
    <i class="fa fa-angle-up"></i>
</div>
<!-- /scroll top -->



<!--Modals-->
<!--Panel Question Modal-->
<div class="modal" id="panel-question">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <i class="fa fa-question"></i> </div>
            <div class="modal-body text-center">How Do you Do?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!--Power Widgets Modal-->
<div class="modal" id="delete-widget">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <i class="fa fa-lock"></i> </div>
            <div class="modal-body text-center">
                <p>Are you sure to delete this widget?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="trigger-deletewidget-reset">Cancel</button>
                <button type="button" class="btn btn-primary" id="trigger-deletewidget">Delete</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!--Sign Out Dialog Modal-->
<div class="modal" id="signout">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <i class="fa fa-lock"></i> </div>
            <div class="modal-body text-center">Are You Sure Want To Sign Out?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="yesigo">Ok</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!--Lock Screen Dialog Modal-->
<div class="modal" id="lockscreen">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <i class="fa fa-lock"></i> </div>
            <div class="modal-body text-center">Are You Sure Want To Lock Screen?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="yesilock">Ok</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
</body>

</html>