<!DOCTYPE html>
<html ng-app="app">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php foreach ($this->css as $css): ?>
    <link rel="stylesheet" type="text/css" href="<?=$css?>">
<?php endforeach; ?>

<?php foreach ($this->scripts as $script): ?>
    <script type="text/javascript" src="<?=$script?>"></script>
<?php endforeach; ?>

</head>

<body>

<!--Smooth Scroll-->
<div class="smooth-overflow">
    <!--Navigation-->
    <nav class="main-header clearfix" role="navigation"> <a class="navbar-brand" href="index.html"><span class="text-blue">RASPBERRY</span><span class="text-orange">ADMIN</span></a>

    </nav>

    <!--/Navigation-->

    <!--MainWrapper-->
    <div class="main-wrap">

        <!--Main Menu-->
        <div class="responsive-admin-menu">
            <div class="responsive-menu">ORB
                <div class="menuicon"><i class="fa fa-angle-down"></i></div>
            </div>
            <ul id="menu">
                <li class=""><a href="#" class="submenu downarrow" data-id="tables-sub" title="Tables"><i class="entypo-facebook-squared"></i><span> Facebook API</span></a>
                    <!-- Tables Sub-Menu -->
                    <ul id="tables-sub" class="accordion" style="display: block;">
                        <li><a href="admin-tables.html" title="Timeline"><span> Покатушки</span></a></li>
                        <li><a href="admin-datatables.html" title="Profile"></i><span> PHP</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!--/MainMenu-->

        <!--Content Wrapper-->
        <div class="content-wrapper"><!--Horisontal Dropdown-->

            <!--Breadcrumb-->
            <div class="breadcrumb clearfix">
                <ul>
                    <li><a href="index.html"><i class="fa fa-home"></i></a></li>
                    <li><a href="index.html">Facebook API</a></li>
                    <li class="active">Покатушки</li>
                </ul>
            </div>
            <!--/Breadcrumb-->

            <div class="page-header">
                <h1><?=$this->get('title', 'Default')?></h1>
            </div>

            <?=$this->getContent();?>

            <!-- /Widgets Row End Grid-->
        </div>
        <!-- / Content Wrapper -->
    </div>
    <!--/MainWrapper-->
</div>
<!--/Smooth Scroll-->



</body>

</html>