<div class="row" >
    <div class="col-md-9 bootstrap-grid sortable-grid ui-sortable">
        <!-- New widget -->


        <!-- End .powerwidget -->
        <div class="powerwidget cold-grey powerwidget-sortable" id="table1" data-widget-editbutton="false" role="widget"
             style="">
            <header role="heading">
                <h2>Список приложений</h2>
                <div class="powerwidget-ctrls" role="menu"><a href="#" class="button-icon powerwidget-delete-btn"><i
                            class="fa fa-times-circle"></i></a> <a href="#"
                                                                   class="button-icon powerwidget-fullscreen-btn"><i
                            class="fa fa-arrows-alt "></i></a> <a href="#" class="button-icon powerwidget-toggle-btn"><i
                            class="fa fa-chevron-circle-up "></i></a></div>
                <span class="powerwidget-loader"></span></header>
            <div class="inner-spacer" role="content">
                <table class="table table-condensed table-bordered margin-0px">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th width="90px">Авторизация</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="text-dark-blue"><strong>Велопокатушки (Киев)</strong></td>
                        <td><a href="" class="btn btn-warning btn-green btn-sm">Группа</a></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-3 bootstrap-grid sortable-grid ui-sortable">
        <!-- New widget -->


        <!-- End .powerwidget -->
        <div class="powerwidget cold-grey powerwidget-sortable" id="table1" data-widget-editbutton="false" role="widget"
             style="">
            <header role="heading">
                <h2>Список приложений</h2>
                <div class="powerwidget-ctrls" role="menu"><a href="#" class="button-icon powerwidget-delete-btn"><i
                            class="fa fa-times-circle"></i></a> <a href="#"
                                                                   class="button-icon powerwidget-fullscreen-btn"><i
                            class="fa fa-arrows-alt "></i></a> <a href="#" class="button-icon powerwidget-toggle-btn"><i
                            class="fa fa-chevron-circle-up "></i></a></div>
                <span class="powerwidget-loader"></span></header>
            <div class="inner-spacer" role="content">
                <table class="table table-condensed table-bordered margin-0px">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th width="90px">Авторизация</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->apps as $app): ?>
                        <tr>
                            <td class="text-dark-blue"><strong><a target="_blank"
                                                                  href="https://developers.facebook.com/apps/<?= $app->getAppId() ?>/dashboard/"><?= $app->getName() ?></a></strong>
                            </td>
                            <td><a href="<?= $app->getRedirectUrl() ?>" class="btn btn-warning btn-sm">Авторизация</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /Inner Row Col-md-12 -->
</div>
